### ISSUE TITLE
Add a Databases Section

### ISSUE THREAD

**Issue by gravitythread** [StanimirIglev/awesome-xml#4]
XML is cool because a collection of XML files is kind of like a database. There are proper database applications that run with this idea.

Just a few:
 - MarkLogic
 - BaseX
 - ExistDB

**Comment by StanimirIglev** [comment]
This is an excellent suggestion and I have been planning to add a section on the topic, but since I have not used XML in this context, I am not very familiar with the awesome technologies available.
I will for sure spend some time researching what is out there and you should see an XML database section in the near future.
Of course, if you are already familiar with the available awesomeness and would like to add them, you are more than welcome to open a pull request.
